function timadj(cutname,timname,outname);
% TIMADJ Adjust 2nd set of cut data to have same segment lengths as first set
% function timadj(cutname,timname,outname);
% timadj: Version 2.2.98
%
%   Description
%       Mainly for matching audio files from DAT to EMA recordings
%       Data in cutfile cutname provides the reference lengths
%       Data in timname is the data to be adjusted, e.g data derived from synch pulse
%       Program transfers labels and comment etc. from cutname to outname
%       MAT file cutname will probably have been generated by a program
%       like emmaproa+dat2mat_ii
%
%   See Also
%       GETLSBC_II EMMAPROA DAT2MAT_II

functionname='timadj: Version 2.2.98';
namestr=['<Start of Comment> ' functionname crlf];
cutdata=mymatin(cutname,'data');
timdata=mymatin(timname,'data');
cutcomment=mymatin(cutname,'comment','No control cutfile comment');
timcomment=mymatin(timname,'comment','No synch file comment');

if size(cutdata,1) ~= size(timdata,1)
    newtim=[];
    disp ('CUT and SYNCH data do not match');
    return
end;
namestr=[namestr 'Reference cut file, Raw synch file, Adjusted timer file' crlf];
namestr=[namestr cutname ' ' timname ' ' outname crlf];
cutlength=cutdata(:,2)-cutdata(:,1);
timlength=timdata(:,2)-timdata(:,1);
dd=cutlength-timlength;
disp ('Time differences (ms): Max/Min/Mean(abs)');
disp ([max(dd) min(dd) mean(abs(dd))]*1000);

namestr=[namestr 'Time differences (ms): Max/Min/Mean(abs)' crlf];
namestr=[namestr num2stre([max(dd) min(dd) mean(abs(dd))]*1000) crlf];



dd=dd./2;
newtim=timdata;
newtim(:,1)=newtim(:,1)-dd;
newtim(:,2)=newtim(:,1)+cutlength;

data=newtim;

namestr=[namestr 'Comment from control cut file================' crlf];
namestr=[namestr cutcomment crlf];
namestr=[namestr 'Comment from synch file================' crlf];
namestr=[namestr timcomment crlf];
namestr=[namestr '<End of Comment> ' functionname crlf];
comment=namestr;
%copy cutfile to outfile, then insert modified variables

copyfile([cutname '.mat'],[outname '.mat']);

save(outname,'data','comment','-append');

%      mymatout(outname,str2mat('data','comment'),data,comment);


