function adjsync4videox(syncfile,outsuffix,trialtimes,trialnums,videotimes);
% ADJSYNC4VIDEOX Adjust sync file to match video data stream
% function adjsync4videox(syncfile,outsuffix,trialtimes,trialnums,videotimes);
% ADJSYNC4VIDEOX: Version 28.7.10
%
%	Syntax
%		syncfile: Normally file generated by getlsb from raw sony data file
%		trialtimes, trialnums, videotimes:
%			all vectors of 2 values, specifying two timepoints to use in
%			aligning the sony and the video data streams
%			trialtimes: times relative to trial start (e.g obtained by
%			loading wav file of individual trial into praat)
%			trialnums: Numbers of the trials for the time points in
%			trialtimes
%			videotimes: time of the corresponding points in the full video
%				data stream (e.g load wav file of complete recording into
%				praat)

functionname='ADJSYNC4VIDEOX: Version 28.7.10';

	load(syncfile);
	
	v=find(trialnums(1)==data(:,4));
	tt1=trialtimes(1)+data(v,1);
	v=find(trialnums(2)==data(:,4));
	tt2=trialtimes(2)+data(v,1);
	
	disp('sony times, and difference');
	disp([tt1 tt2 tt2-tt1]);
	disp('video times, and difference');
	disp([videotimes(1) videotimes(2) diff(videotimes)]);
disp('sony dif. - video dif. ');
disp([tt2-tt1]-diff(videotimes));
	
	newdata=interp1([tt1 tt2],videotimes,data(:,1:2),'linear','extrap');

%	keyboard;

	data(:,1:2)=newdata;
comment=['Trial times : ' num2str(trialtimes) crlf 'Trial numbers : ' int2str(trialnums) crlf 'Video times : ' num2str(videotimes) crlf comment];
comment=framecomment(comment,functionname);

	
copyfile([syncfile '.mat'],[syncfile outsuffix '.mat']);

save([syncfile outsuffix],'data','comment','-append');
