Description of getsynchWaveNIDAQ_mkt
Home > NDIWAVES > getsynchWaveNIDAQ_mkt.m
getsynchWaveNIDAQ_mkt
PURPOSE
Trial number might be incorrect
SYNOPSIS
function getsynchWaveNIDAQ_mkt(daqFile,smpte_chn_NI,NDIsessionroot,smpte_chn_WAVE,session,filelist,sessfile)
DESCRIPTION
 Trial number might be incorrect
 so far this is  a version for just one large DAQ file
  smpte_chn_NI: channel on the NI daq file
CROSS-REFERENCE INFORMATION
This function calls:
NDIWaveParseSessionFile sessionDir="C:\\ndigital\\collections"
NDIimport Purpose: - Import NDI WAVE FILE,
SMPTE_dec % SMPTE audio decoder v2.4
This function is called by:
SUBFUNCTIONS
functionname=[rmextension(mfilename),
DOWNLOAD
getsynchWaveNIDAQ_mkt.m
SOURCE CODE
function getsynchWaveNIDAQ_mkt(daqFile,smpte_chn_NI,NDIsessionroot,smpte_chn_WAVE,session,filelist,sessfile)
% Trial number might be incorrect
% so far this is  a version for just one large DAQ file
%  smpte_chn_NI: channel on the NI daq file
cgdebug=0;
timingDebug=1;
smptedescr=str2mat('hh','mm','ss','ff','audio_time');
namestr='';
functionname=[rmextension(mfilename), ': Version 20-Oct-2011'];
disp(sessfile)
private.sesscfg=NDIWaveParseSessionFile(sessfile);
cutname=[daqFile 'syncCh',num2str(smpte_chn_NI)];
namestr=[namestr 'Output cut file: ' cutname crlf];
disp (functionname);
maxcut=20000;
[abint,abnoint,abscalar,abnoscalar]=abartdef;
timdat=ones(maxcut,4)*NaN;
timdat(:,3)=0;
maxtlen=length(int2str(maxcut));
cutlabel=setstr(zeros(maxcut,maxtlen));
data=nan(length(filelist),4);
data(:,3)=0;
totalcuts=0;
for fnum=filelist
    %% ANALYSIS OF NATIONAL INSTRUMENTS NIDAQ SMPTE starts here:
    NIDAQ=load([daqFile int2str0vec(filelist(fnum))]);
    private.NIDAQ=NIDAQ.private;
    disp('decoding NIDAQ file ...')
    NILEN=length(NIDAQ.DAQData)/NIDAQ.srate;
    disp([' NIDAQ length (sec.) : ' num2str(NILEN)]);
    % keyboard
    % [smpte_NI smpte_str_NI,errN_NI] = SMPTE_dec(NIDAQ.DAQData(:,smpte_chn_NI),NIDAQ.srate,25,0);
    soundout=soundsc_cg(NIDAQ.DAQData(:,smpte_chn_NI),NIDAQ.srate);
    [smpte_NI smpte_str_NI,errN_NI] = SMPTE_dec(soundout,NIDAQ.srate,25,0);
    % soundout=soundsc_cg(NIDAQ.DAQData(:,smpte_chn_NI),NIDAQ.srate);
    % [smpte_NI smpte_str_NI,errN_NI] = SMPTE_dec(soundout,NIDAQ.srate,25,0);
    smpteDur_NI=smpte_NI(end,end)-smpte_NI(1,end);
    if timingDebug
        disp([ 'last SMPTE frame at ' num2str(smpte_NI(end,end))])
        disp([ 'first SMPTE frame at ' num2str(smpte_NI(1,end))])
        % Das ist die Dauer der Art Daten
        disp(['length of Code according to SMPTE NI capture  ( last - first ) ' num2str(smpteDur_NI)])
    end
    diary getsynch_NIDAQ.log
    if cgdebug
        daqinfo = daqread(daqFile,'info');
        adlink_chn=cat(1,daqinfo.ObjInfo.Channel.Index)';
        adlink_desc=char(daqinfo.ObjInfo.Channel.ChannelName);
        adlink_unit=daqinfo.ObjInfo.Channel.Units;
        % Scale
        adlink_signalzero=cat(1,daqinfo.ObjInfo.Channel.NativeOffset);
    end
    lastdat=0;
    nchanin=NIDAQ.nchan;
    sftemp=NIDAQ.srate;
    dectemp=0;
    sfchannel=sftemp/(dectemp+1);
    sfbase=sfchannel*nchanin;
    sf=sfchannel;
    totalsamp=size(NIDAQ.DAQData,1); % assuming that
    lastdat=0;
    % lastdat=1;   % I have to set this to 1, is 0 in Phil original!
    icut=1;
    nsamp=0;
    mystart=1;
    % read NI-DAQ Data
    %samplerateNIDAQ=25600;
    %NI=load('Z:/myfiles/Matlab/cgm/NDIWAVES/DAQData');
    % smpte_NI TC: 5 column matrix with hh mm ss ff audio_time
    %smpte_chn_NI=1;
    %[smpte_NI smpte_str_NI,errN_NI] = SMPTE_dec(NIDAQ.DAQData(:,smpte_chn_NI),NIDAQ.srate,25,0);
    smpteDur_NI=smpte_NI(end,end)-smpte_NI(1,end);
    if timingDebug
        disp([ 'last SMPTE frame at ' num2str(smpte_NI(end,end))])
        disp([ 'first SMPTE frame at ' num2str(smpte_NI(1,end))])
        % Das ist die Dauer der Art Daten
        disp(['length of Code according to SMPTE NI capture  ( last - first ) ' num2str(smpteDur_NI)])
    end
    %% NATIONAL INSTRUMENTS NIDAQ Ends here:
    %%
    totalcuts=totalcuts+1;
    %% ANALYSIS of NDI WAVE SMPTE starts here
    infWavSynch = [NDIsessionroot session '/MySession_' session '_' int2str0(fnum,3) '_sync.wav'];
    disp('++++++++++++++++++++++++++++++++++++++++++')
    disp('')
    disp(['Processing file ' infWavSynch])
    disp('')
    %[dataSy,samplerateSy,NBITSSy,opts]=wavread(infWavSynch);
    infile=[NDIsessionroot session '/rawdata/MySession_' session '_' int2str0(fnum,3) '.wav']
    [dataSYNCH,samplerate,NBITS]=wavread(infile);
    if timingDebug
        %disp(['length of synched WAVE data in sec.: ' num2str(length(dataSy)/samplerateSy)])
        disp(['length of UNsynched WAVE data in sec.: ' num2str(length(dataSYNCH)/samplerate)])
    end
    [smpte smpte_str,errN] = SMPTE_dec(dataSYNCH(:,2),samplerate,25,0);
    smpteDur=smpte(end,end)-smpte(1,end);
    if timingDebug
        disp([ 'first SMPTE frame at ' num2str(smpte(1,end))])
        disp([ 'last SMPTE frame at ' num2str(smpte(end,end))])
    end
    %% ANALYSIS of NDI WAVE SMPTE ENDS here
    %% Articulatory Data - Spread Sheet
    % TODO: Stimmt die Time Axis?
    srArt=private.sesscfg.samplerate;
    insheet=[NDIsessionroot session '/MySession_' session '_' int2str0(fnum,3) '_sync.tsv'];
    disp(['reading NDI sheet ' insheet])
    %[dataArt,descr]=importfile(insheet);
    [dataArt,descr]=NDIimport(insheet);
    durDiff=dataArt(end,1)-dataArt(1,1);
    if timingDebug
        disp(['length of Art data in sec. from Dat Leng: ' num2str(length(dataArt)/srArt)])
        disp([' first articulatory Stamp: ' num2str(dataArt(1,1))])
        disp([' last articulatory Stamp: ' num2str(dataArt(end,1))])
        disp([' Diff Art: ' num2str(durDiff)])
    end
    [c,iNIDAQ,iWAVE]=intersect(smpte_NI(:,1:4),smpte(:,1:4),'rows');
    % Startpoint of NI Sample
    TStartNIDAQ=smpte_NI(iNIDAQ([1]),5)-smpte(iWAVE([1]),5);
    % Endpoint of NI Sample - Use the duration of already synched wav-File to calculate NIDAQ-EOF:
    wavduration=length(dataSYNCH)/samplerate;
    TEndNIDAQ=TStartNIDAQ+wavduration;
    disp(['NI: ' num2str(TStartNIDAQ) ' - ' num2str(TEndNIDAQ) ' (' num2str(wavduration) ')'])
    disp(smptedescr);
    disp('NI first and last frame:')
    disp(smpte_NI([1 end],:));
    disp('WAVE first and last frame:')
    disp(smpte([1 end],:));
    %keyboard
    data(totalcuts,1)=TStartNIDAQ;
    data(totalcuts,2)=TEndNIDAQ;
    data(totalcuts,4)=fnum;
    cutlabel(totalcuts,:)=int2str0(totalcuts,maxtlen);
end
samplerate=NIDAQ.srate;
comment=[namestr];
%comment=[namestr sonycomment];
comment=framecomment(comment,functionname)
[descriptor,unit,valuelabel]=cutstrucn;
label=cutlabel(1:totalcuts,:)
% private
disp(data)
eval (['save ' cutname ' data label descriptor unit comment valuelabel samplerate private']);
%eval (['save ' cutname ' data label descriptor unit comment private valuelabel']);
diary dodo
diary off